// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk9wQmxeSLkjpIOrZqg4Uog43xDMDODrA',
    appId: '1:710742246558:web:ddb0e70f5fe5f1647ce78f',
    messagingSenderId: '710742246558',
    projectId: 'seismic-ground-410711',
    authDomain: 'seismic-ground-410711.firebaseapp.com',
    storageBucket: 'seismic-ground-410711.appspot.com',
    measurementId: 'G-WQ4KKCME8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYyFAaJ8LayV6v31aKionhtsw5vLMMu4A',
    appId: '1:710742246558:android:4028b74eee7ecbba7ce78f',
    messagingSenderId: '710742246558',
    projectId: 'seismic-ground-410711',
    storageBucket: 'seismic-ground-410711.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADBoJaUlQJ03BkglRinwT9yYnNXDmyWOE',
    appId: '1:710742246558:ios:2deb48a2712e25f67ce78f',
    messagingSenderId: '710742246558',
    projectId: 'seismic-ground-410711',
    storageBucket: 'seismic-ground-410711.appspot.com',
    iosBundleId: 'com.store.otto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADBoJaUlQJ03BkglRinwT9yYnNXDmyWOE',
    appId: '1:710742246558:ios:7a3963655f076b667ce78f',
    messagingSenderId: '710742246558',
    projectId: 'seismic-ground-410711',
    storageBucket: 'seismic-ground-410711.appspot.com',
    iosBundleId: 'com.example.master.RunnerTests',
  );
}
